ARG commit=latest
FROM elifesciences/peerscout:${commit}
ENV DEBUG=1

USER elife
COPY --chown=elife:elife requirements-debug.txt ${PROJECT_FOLDER}/
RUN venv/bin/pip install -r requirements-debug.txt

USER root
RUN mkdir build/ && chown www-data:www-data build/

USER www-data
CMD ["./project_tests.sh"]
