# we don't have a elife base image yet for node, so we use directly the official one
FROM node:8.12.0-stretch AS client

USER node

RUN mkdir /home/node/client
WORKDIR /home/node/client

COPY --chown=node:node client/package.json client/package-lock.json ./
RUN npm ci

COPY --chown=node:node client ./

RUN npm run bundle
