ARG base_image
FROM ${base_image}

USER root
RUN mkdir build/ && chown www-data:www-data build/
RUN touch app.cfg && chown www-data:www-data app.cfg

USER elife

ENV COVERAGE_FILE=${PROJECT_FOLDER}/build/.coverage
COPY --chown=elife:elife project_tests.sh pytest.ini .pylintrc .flake8 setup.py ${PROJECT_FOLDER}/
COPY --chown=elife:elife tests/ ${PROJECT_FOLDER}/tests/

USER www-data
CMD ["./project_tests.sh"]
